Mamba/Areas/Admin/ViewModels/Settings/CreateSettingsVM.cs
using System.ComponentModel.DataAnnotations;

namespace Mamba.Areas.Admin.ViewModels
{
    public class CreateSettingsVM
    {
        [Required(ErrorMessage = "Is Reqiured")]
        public string Key { get; set; }

        [Required(ErrorMessage = "Is Reqiured")]
        public string Value { get; set; }
    }
}

Mamba/Areas/Admin/ViewModels/Settings/UpdateSettingsVM.cs
using System.ComponentModel.DataAnnotations;

namespace Mamba.Areas.Admin.ViewModels
{
    public class UpdateSettingsVM
    {
        [Required(ErrorMessage = "Is Reqiured")]
        public string Key { get; set; }

        [Required(ErrorMessage = "Is Reqiured")]
        public string Value { get; set; }
    }
}

Mamba/Models/Settings.cs
namespace Mamba.Models
{
    public class Settings : BaseEntity
    {
        public string Key { get; set; } = null!;
        public string Value { get; set; } = null!;
    }
}

Mamba/Areas/Admin/Controllers/SettingsController.cs
using Mamba.Areas.Admin.ViewModels;
using Mamba.DAL;
using Mamba.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Mamba.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class SettingsController : Controller
    {
        private readonly AppDbContext _context;

        public SettingsController(AppDbContext context)
        {
            _context = context;
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index()
        {
            ICollection<Settings> items = await _context.Settings.ToListAsync();
            return View(items);
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateSettingsVM create)
        {
            if (!ModelState.IsValid) return View(create);
            bool result = await _context.Settings.AnyAsync(x => x.Key.Trim().ToLower() == create.Key.Trim().ToLower());
            if (result)
            {
                ModelState.AddModelError("Key", "Is exists");
                return View(create);
            }
            Settings item = new Settings
            {
                Key = create.Key,
                Value = create.Value
            };

            await _context.Settings.AddAsync(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Settings item = await _context.Settings.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();
            UpdateSettingsVM update = new UpdateSettingsVM
            {
                Key = item.Key,
                Value = item.Value
            };
            return View(update);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateSettingsVM update)
        {
            if (!ModelState.IsValid) return View(update);

            Settings existed = await _context.Settings.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) return NotFound();

            bool result = await _context.Settings.AnyAsync(x => x.Key.Trim().ToLower() == update.Key.Trim().ToLower() && x.Id != id);
            if (result)
            {
                ModelState.AddModelError("Key", "Is exists");
                return View(update);
            }

            existed.Key = update.Key;
            existed.Value = update.Value;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Settings item = await _context.Settings.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            _context.Settings.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Mamba/Areas/Admin/Views/Settings/Create.cshtml
@model CreateSettingsVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Default form</h4>
            <p class="card-description">
                Basic form layout
            </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Key">Key</label>
                    <input asp-for="Key" class="form-control" placeholder="Key">
                    <span asp-validation-for="Key"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Value">Value</label>
                    <input asp-for="Value" class="form-control" placeholder="Value">
                    <span asp-validation-for="Value"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-action="Index" asp-controller="Settings">Cancel</button>
            </form>
        </div>
    </div>
</div>

Mamba/Areas/Admin/Views/Settings/Index.cshtml
@model ICollection<Settings>

@{
    int count = 0;
}

<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Settings Table</h4>
                <a class="btn btn-primary" asp-action="Create" asp-controller="Settings">Create</a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Key</th>
                            <th>Value</th>
                            <th>Settings</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>@count</td>
                                <td>@item.Key</td>
                                <td>@item.Value</td>
                                <td>
                                    <a asp-action="Update" asp-controller="Settings" asp-route-id="@item.Id" class="btn btn-primary">Update</a>
                                    <a asp-action="Delete" asp-controller="Settings" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Mamba/Areas/Admin/Views/Settings/Update.cshtml
@model UpdateSettingsVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Default form</h4>
            <p class="card-description">
                Basic form layout
            </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Key">Key</label>
                    <input asp-for="Key" class="form-control" placeholder="Key">
                    <span asp-validation-for="Key"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Value">Value</label>
                    <input asp-for="Value" class="form-control" placeholder="Value">
                    <span asp-validation-for="Value"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-action="Index" asp-controller="Settings">Cancel</button>
            </form>
        </div>
    </div>
</div>