Mamba/Areas/Admin/ViewModels/Position/CreatePositionVM.cs
using System.ComponentModel.DataAnnotations;

namespace Mamba.Areas.Admin.ViewModels
{
    public class CreatePositionVM
    {
        [Required(ErrorMessage = "Is Reqiured")]
        public string Name { get; set; }
    }
}

Mamba/Areas/Admin/ViewModels/Position/UpdatePositonVM.cs
using System.ComponentModel.DataAnnotations;

namespace Mamba.Areas.Admin.ViewModels
{
    public class UpdatePositonVM
    {
        [Required(ErrorMessage = "Is Reqiured")]
        public string Name { get; set; }
    }
}

Mamba/Models/Position.cs
namespace Mamba.Models
{
    public class Position : BaseNameEntity
    {
        public ICollection<Team>? Teams { get; set; }
    }
}

Mamba/Areas/Admin/Controllers/PositionController.cs
using Mamba.Areas.Admin.ViewModels;
using Mamba.DAL;
using Mamba.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Mamba.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class PositionController : Controller
    {
        private readonly AppDbContext _context;

        public PositionController(AppDbContext context)
        {
            _context = context;
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index()
        {
            ICollection<Position> items = await _context.Positions.ToListAsync();
            return View(items);
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreatePositionVM create)
        {
            if (!ModelState.IsValid) return View(create);
            bool result = await _context.Positions.AnyAsync(x => x.Name.Trim().ToLower() == create.Name.Trim().ToLower());
            if (result)
            {
                ModelState.AddModelError("Name", "Is exists");
                return View(create);
            }
            Position item = new Position { Name = create.Name };

            await _context.Positions.AddAsync(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Position item = await _context.Positions.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();
            UpdatePositonVM update = new UpdatePositonVM { Name = item.Name };
            return View(update);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdatePositonVM update)
        {
            if (!ModelState.IsValid) return View(update);

            Position existed = await _context.Positions.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) return NotFound();

            bool result = await _context.Positions.AnyAsync(x => x.Name.Trim().ToLower() == update.Name.Trim().ToLower() && x.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "Is exists");
                return View(update);
            }

            existed.Name = update.Name;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Position item = await _context.Positions.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            _context.Positions.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Mamba/Areas/Admin/Views/Position/Create.cshtml
@model CreatePositionVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Default form</h4>
            <p class="card-description">
                Basic form layout
            </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-action="Index" asp-controller="Position">Cancel</button>
            </form>
        </div>
    </div>
</div>

Mamba/Areas/Admin/Views/Position/Index.cshtml
@model ICollection<Position>
@{
    int count = 0;
}
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Postion Table</h4>
            <a class="btn btn-primary" asp-action="Create" asp-controller="Postion">Create</a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Amount</th>
                            <th>Settings</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>@count</td>

                                <td>@item.Name</td>
                                <td>@item.Teams.Count</td>
                                <td>
                                    <a asp-action="Update" asp-controller="Position" asp-route-id="@item.Id" class="btn btn-primary">Update</a>
                                    <a asp-action="Delete" asp-controller="Position" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Mamba/Areas/Admin/Views/Position/Update.cshtml
@model UpdatePositonVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Default form</h4>
            <p class="card-description">
                Basic form layout
            </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-action="Index" asp-controller="Position">Cancel</button>
            </form>
        </div>
    </div>
</div>